import type { ArtifactSpec } from "@/lib/schemas/artifacts/types";

const cite = (page: number, section?: string, excerpt?: string) => ({
  source: "owner-manual.pdf",
  page,
  section,
  excerpt,
});

export const ARTIFACT_GALLERY_SAMPLES: ArtifactSpec[] = [
  {
    type: "polarity-diagram",
    title: "MIG Solid Core — DCEP Polarity",
    description: "Ground clamp to negative socket, MIG gun to positive socket.",
    process: "mig-solid",
    polarityType: "DCEP",
    groundSocket: "negative",
    electrodeSocket: "positive",
    groundLabel: "Ground Clamp",
    electrodeLabel: "MIG Gun / Spool Gun",
    safetyNotice: "Turn OFF power and unplug before connecting cables.",
    confidence: "high",
    citations: [cite(14, "DCEP Solid Core Setup", "Ground clamp → negative socket")],
    provenance: { source: "owner-manual.pdf", verified: true, extractionMethod: "regex_section" },
  },
  {
    type: "cable-routing-diagram",
    title: "TIG Cable Routing",
    description: "Torch and work clamp socket assignments for TIG setup.",
    process: "tig",
    routes: [
      { id: "r1", cable: "Ground Clamp Cable", from: "Ground clamp", to: "Positive (+) socket", socket: "positive", color: "orange" },
      { id: "r2", cable: "TIG Torch Cable", from: "TIG torch", to: "Negative (−) socket", socket: "negative", color: "blue" },
    ],
    citations: [cite(24, "TIG Setup", "Ground clamp in positive socket")],
    confidence: "high",
    provenance: { source: "owner-manual.pdf", verified: true },
  },
  {
    type: "duty-cycle-calculator",
    title: "MIG Duty Cycle @ 240V",
    description: "Interactive duty-cycle timeline from manual specifications.",
    process: "mig",
    voltage: 240,
    defaultAmps: 200,
    ratedDutyPercent: 25,
    ratedAmps: 200,
    citations: [cite(7, "Specifications", "25% @ 200 A")],
    confidence: "high",
    provenance: { source: "owner-manual.pdf", verified: true, extractionMethod: "pdfplumber_specs_table" },
  },
  {
    type: "settings-configurator",
    title: "Mild Steel 1/8\" MIG Settings",
    description: "Recommended settings from selection chart (multimodal interpretation may be required).",
    process: "mig",
    material: "Mild Steel",
    thickness: '1/8"',
    wireType: "Solid core",
    wireDiameter: "0.030\"",
    gas: "C25",
    inputVoltage: 240,
    recommended: { voltage: "See chart", wireSpeed: "See chart", notes: "Refer to selection-chart.pdf" },
    setupChecklist: [
      { id: "s1", label: "Verify DCEP polarity", completed: false },
      { id: "s2", label: "Install correct contact tip", completed: false },
      { id: "s3", label: "Set wire tension", completed: false },
    ],
    polarityRef: { groundSocket: "negative", electrodeSocket: "positive", polarityType: "DCEP" },
    supportingEvidence: ["selection-chart.pdf p.1", "owner-manual.pdf p.14"],
    citations: [cite(7, "Specifications")],
    confidence: "medium",
  },
  {
    type: "troubleshooting-flow",
    title: "Porosity Troubleshooting",
    description: "Structured flow for porosity in weld metal.",
    currentQuestion: "Are you using shielding gas with solid-core wire?",
    observations: ["Flux-core wire", "Pinholes in weld face"],
    branches: [
      { id: "q1", label: "Using solid core MIG with gas?", kind: "question", nextId: "c1" },
      { id: "c1", label: "Shielding gas bottle empty", kind: "cause" },
      { id: "a1", label: "Check gas bottle and regulator flow", kind: "action" },
    ],
    eliminatedCauses: ["Dirty contact tip (ruled out)"],
    nextRecommendedCheck: "Verify polarity is DCEP for MIG solid core.",
    citations: [cite(43, "Porosity in the Weld Metal")],
    confidence: "high",
  },
  {
    type: "diagnostic-hypothesis-board",
    title: "Porosity — Ranked Causes",
    description: "Top hypotheses narrowed from manual troubleshooting table.",
    evidenceSummary: "Flux-core wire + porosity pattern suggests gas/polarity/CTWD checks first.",
    hypotheses: [
      { id: "h1", label: "Incorrect polarity", confidence: 0.32, evidenceFor: ["owner-manual.pdf p.43"], evidenceAgainst: [], missingObservation: "Confirm DCEP vs DCEN" },
      { id: "h2", label: "Insufficient shielding gas", confidence: 0.28, evidenceFor: ["owner-manual.pdf p.43"], evidenceAgainst: [] },
      { id: "h3", label: "Dirty workpiece", confidence: 0.2, evidenceFor: ["owner-manual.pdf p.43"], evidenceAgainst: [] },
      { id: "h4", label: "CTWD too long", confidence: 0.12, evidenceFor: [], evidenceAgainst: [], ruledOut: false },
    ],
    citations: [cite(43)],
    confidence: "medium",
  },
  {
    type: "manual-figure",
    title: "Specifications Table",
    caption: "Rated duty cycles and current ranges — MIG/TIG/Stick",
    assetId: "owner-manual-p07",
    source: "owner-manual.pdf",
    page: 7,
    citations: [cite(7, "Specifications")],
    confidence: "high",
  },
  {
    type: "annotated-manual-figure",
    title: "Front Panel Controls",
    caption: "Positive socket, negative socket, and MIG gun cable socket",
    assetId: "owner-manual-p08",
    source: "owner-manual.pdf",
    page: 8,
    regions: [
      { id: "pos", label: "Positive socket", x: 62, y: 38, width: 12, height: 10, description: "Work clamp / electrode positive" },
      { id: "neg", label: "Negative socket", x: 28, y: 38, width: 12, height: 10, description: "Torch or gun negative" },
    ],
    callouts: [
      { id: "c1", label: "Positive (+) socket", x: 68, y: 35, targetRegionId: "pos" },
      { id: "c2", label: "Negative (−) socket", x: 34, y: 35, targetRegionId: "neg" },
    ],
    citations: [cite(8, "Front Panel Controls")],
    confidence: "high",
  },
  {
    type: "component-map",
    title: "Front Panel Component Map",
    description: "Interactive map of operator controls.",
    view: "front_panel",
    components: [
      { id: "lcd", name: "LCD Display", x: 50, y: 25, description: "Process and settings readout", highlighted: true },
      { id: "pos", name: "Positive Socket", x: 72, y: 55, description: "Polarity terminal +" },
      { id: "neg", name: "Negative Socket", x: 28, y: 55, description: "Polarity terminal −" },
      { id: "pwr", name: "Power Switch", x: 15, y: 30 },
    ],
    citations: [cite(8, "Front Panel Controls")],
    confidence: "high",
  },
  {
    type: "step-by-step-checklist",
    title: "MIG Solid Core Setup",
    description: "Setup sequence from owner manual.",
    steps: [
      { id: "1", label: "Turn OFF power and unplug", safetyCritical: true, completed: false },
      { id: "2", label: "Connect ground clamp to negative socket", completed: false },
      { id: "3", label: "Connect MIG gun to positive socket", completed: false },
      { id: "4", label: "Attach gas regulator and set flow", completed: false },
      { id: "5", label: "Set wire tension", detail: "Wire should bend, not stop, at block", completed: false },
    ],
    safetyNotice: "Read ENTIRE safety section before setup.",
    citations: [cite(14, "MIG Setup")],
    confidence: "high",
  },
  {
    type: "weld-defect-comparison",
    title: "Defect Comparison — Porosity",
    description: "Match user-reported defect to manual exemplars.",
    defectName: "Porosity",
    userDescription: "Small holes scattered in the weld bead",
    exemplars: [
      { id: "e1", label: "Porosity (gas)", description: "Rounded cavities from trapped gas", source: "owner-manual.pdf", page: 43, matchScore: 0.85 },
      { id: "e2", label: "Undercut", description: "Groove along toe of weld", source: "owner-manual.pdf", page: 43, matchScore: 0.2 },
    ],
    citations: [cite(43, "Troubleshooting")],
    confidence: "medium",
    uncertaintyNotes: [],
    possibleCategories: ["porosity"],
    visualObservations: [],
    potentialCauses: [],
  },
  {
    type: "configuration-summary",
    title: "Configuration Validation",
    description: "Stated setup vs manual requirements.",
    process: "MIG Solid Core",
    inputVoltage: 240,
    polarity: "DCEP",
    consumables: ["Solid wire 0.030\"", "C25 gas"],
    components: ["Contact tip", "Gas nozzle"],
    validationStatus: "verified",
    warnings: [],
    contradictions: [],
    citations: [cite(14)],
    confidence: "high",
    provenance: { source: "owner-manual.pdf", verified: true },
  },
];
